Update create_rel_tag.yml

diff --git a/.github/workflows/create_rel_tag.yml b/.github/workflows/create_rel_tag.yml
--- a/.github/workflows/create_rel_tag.yml
+++ b/.github/workflows/create_rel_tag.yml
@@ -55,7 +55,7 @@ jobs:
               git commit -m "Update params.env with new release tags [$${{ github.event.inputs.tag_name }}]"
               git push
 
-
+   
    changelog:
       name: Build Changelog
       needs: update-params-env
@@ -69,6 +69,15 @@ jobs:
           uses: actions/checkout@v2
         - name: changelog print old tag
           run: echo  "old_tag is $old_tag"
+        - name: Compare tags
+          id: compare_tags
+          run: |
+            latest_tag=$old_tag
+            new_tag=${{ github.event.inputs.tag_name }}
+            echo "Latest Tag: $latest_tag"
+            echo "New Tag: $new_tag"
+            node -e "const [latestMajor, latestMinor, latestPatch] = process.env.LATEST_TAG.substring(1).split('.'); const [newMajor, newMinor, newPatch] = process.env.NEW_TAG.substring(1).split('.'); if (latestMajor > newMajor || (latestMajor == newMajor && latestMinor > newMinor) || (latestMajor == newMajor && latestMinor == newMinor && latestPatch >= newPatch)) { console.log('Error: New tag is not greater than the latest tag.'); process.exit(1); }"
+
         - name: Build Changelog
           id: build_changelog
           uses: mikepenz/release-changelog-builder-action@v4
@@ -78,7 +87,6 @@ jobs:
             token: ${{ github.TOKEN }}
         - name: print_output
           run: echo "${{ toJson(steps.build_changelog.outputs) }}"
- #echo "Changelog output:" ${{ steps.build_changelog.outputs }}
 
 
           
