Update create_rel_tag.yml

diff --git a/.github/workflows/create_rel_tag.yml b/.github/workflows/create_rel_tag.yml
--- a/.github/workflows/create_rel_tag.yml
+++ b/.github/workflows/create_rel_tag.yml
@@ -23,16 +23,22 @@ jobs:
       
       - name: Get latest tag
         id: get_tag
-        run: echo "old_tag_name=$(git ls-remote --tags origin | awk -F"/" '{print $3}' | grep -v '{}' | sort -V | tail -n1)" >> $GITHUB_OUTPUT
+        run: | 
+          echo "old_tag_name=$(git ls-remote --tags origin | awk -F"/" '{print $3}' | grep -v '{}' | sort -V | tail -n1)" >> $GITHUB_OUTPUT
+          echo $old_tag_name
+      - name: print tag
+        id: print
+        run: ${{ steps.fetch-tag.outputs.old_tag }}
       - name: Compare tags
         id: compare_tags
         run: |
-          latest_tag=${{ steps.fetch-tag.outputs.old_tag }}
-          new_tag=${{ github.event.inputs.tag_name }}
+         run: |
+          latest_tag="$GITHUB_OUTPUT"
+          new_tag=v0.0.2
           echo "Latest Tag: $latest_tag"
           echo "New Tag: $new_tag"
-          node -e "const [latestMajor, latestMinor, latestPatch] = process.env.LATEST_TAG.substring(1).split('.'); const [newMajor, newMinor, newPatch] = process.env.NEW_TAG.substring(1).split('.'); if (latestMajor > newMajor || (latestMajor == newMajor && latestMinor > newMinor) || (latestMajor == newMajor && latestMinor == newMinor && latestPatch >= newPatch)) { console.log('Error: New tag is not greater than the latest tag.'); process.exit(1); }"
-
+          node -e "const latestMajor = parseInt(process.env.LATEST_TAG.substring(1).split('.')[0]); const latestMinor = parseInt(process.env.LATEST_TAG.substring(1).split('.')[1]); const latestPatch = parseInt(process.env.LATEST_TAG.substring(1).split('.')[2]); const newMajor = parseInt(process.env.NEW_TAG.substring(1).split('.')[0]); const newMinor = parseInt(process.env.NEW_TAG.substring(1).split('.')[1]); const newPatch = parseInt(process.env.NEW_TAG.substring(1).split('.')[2]); if (latestMajor > newMajor || (latestMajor === newMajor && latestMinor > newMinor) || (latestMajor === newMajor && latestMinor === newMinor && latestPatch >= newPatch)) { console.log('Error: New tag is not greater than the latest tag.'); process.exit(1); }"
+ 
    update-params-env:
         runs-on: ubuntu-latest
         needs: fetch-tag
