Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,15 +31,26 @@ jobs:
   
       - name: Check if tag exists
         id: check_tag
+        shell: python
         run: |
-          if git rev-parse "${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
-            echo "Error: Tag '${{ github.event.inputs.tag_name }}' already exists."
-            exit 1
-            echo "::error ::tag exsistsn"
-          fi
+          # if git rev-parse "${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
+          #   echo "Error: Tag '${{ github.event.inputs.tag_name }}' already exists."
+          #   exit 1
+          #   echo "::error ::tag exsistsn"
+          # fi
+          python3 - <<EOF
+          import subprocess
+          import sys
+
+          try:
+              # Check if the tag exists
+              subprocess.check_call(['git', 'rev-parse', '${{ github.ref }}'])
+          except subprocess.CalledProcessError:
+              # If the tag does not exist, print an error message and exit with code 1
+              print("Error: Tag '${{ github.ref }}' already exists.", file=sys.stderr)
+              sys.exit(1)
+          EOF
         continue-on-error: false
-        strategy:
-          fail-fast: true
       - name: print
         id: print
         run: |
